# Site settings
title: Websites done right.
description: Marko Todorović, Web dev (UI, UX)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Websites done right.
user_description: Building amazing experience
user_title: Marko Todorović, Web dev (UI, UX)
email: todorovic.markonato88@gmail.com
twitter_username: tozaman
github_username: bavariah
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
